In [16]:
import numpy as np
# 1. Create a 1D array of numbers from 0 to 9.
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# 2. Create a 3×3 numpy array of all True’s
arr2 = np.ones(shape=(3,3), dtype='bool')
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
# 3. Given an array as input, print only odd numbers as output
arr3 = arr1[np.where(arr1 % 2 != 0)]
print('Odd numbers:', arr3)

Odd numbers: [1 3 5 7 9]


In [20]:
# 4. Replace all odd numbers in arr with -2
arr1[arr1 % 2 != 0] = -2
print(arr1)

[ 0 -2  2 -2  4 -2  6 -2  8 -2]


In [29]:
# 5. How to reshape an array?
arr4 = np.array([[1,2,3], [4,5,6]])
print('Before reshape :\n', arr4.shape, arr4)
arr4_reshape = arr4.reshape((3,2))
print('After reshape :\n', arr4_reshape.shape, arr4_reshape)

Before reshape :
 (2, 3) [[1 2 3]
 [4 5 6]]
After reshape :
 (3, 2) [[1 2]
 [3 4]
 [5 6]]


In [36]:
# 6. Convert a 1D array to a 2D array with 2 rows
arr5 = np.arange(10)
print(arr5)
arr5_reshape = arr5.reshape((-1,5))
print(arr5_reshape.shape, arr5_reshape)

[0 1 2 3 4 5 6 7 8 9]
(2, 5) [[0 1 2 3 4]
 [5 6 7 8 9]]


In [62]:
# 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples
a = np.array([1,2,3,4,5,6,7,8,9])

# Copying elements of array a to another array
b = np.copy(a[(a % 2 != 0) | (a % 4 == 0)])
print('Array a :',a)
print('Array b :', b)

Array a : [1 2 3 4 5 6 7 8 9]
Array b : [1 3 4 5 7 8 9]


In [71]:
# 8. Given array, check if there are any null values and print them out. 
arr6 = np.array([1, 2, np.NaN, 4, 6, 8, np.NaN])
filter = np.isnan(arr6)
print(arr6[filter])

[nan nan]


In [73]:
# 9. How to replace all missing values with 0 in a numpy array?
arr6[filter] = 0
print(arr6)

[1. 2. 0. 4. 6. 8. 0.]


In [80]:
# 10. How to find the count of each unique number in a NumPy array?
arr7 = np.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
unique, counts = np.unique(arr7, return_counts=True)
for i in unique:
    print(i, '-', counts[i])

0 - 7
1 - 4
2 - 1
3 - 2
4 - 1


In [87]:
# 11. How to convert a numeric to a categorical (text) array?
num_arr = np.array([1,2,3,4,5])
cat_arr =  num_arr.astype(str)
print(cat_arr)

['1' '2' '3' '4' '5']


In [95]:
# 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 
arr8 = np.arange(99,299)
filter = np.where(((arr8 % 5 == 0) | (arr8 % 7 == 0)) & (arr8 % 35 != 0))
print(arr8[filter])

[100 110 112 115 119 120 125 126 130 133 135 145 147 150 154 155 160 161
 165 168 170 180 182 185 189 190 195 196 200 203 205 215 217 220 224 225
 230 231 235 238 240 250 252 255 259 260 265 266 270 273 275 285 287 290
 294 295]


In [100]:
# 13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
arr9 = np.arange(0,15)
reverse_arr9 = arr9[::-1]
print(reverse_arr9)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
